version: 2.1

parameters:
  goImage:
    type: string
    default: "gcr.io/gcr-for-testing/golang:1.20.7"
  arangodbImage:
    type: string
    default: "gcr.io/gcr-for-testing/arangodb/arangodb:3.9.2"
  alpineImage:
    type: string
    default: "gcr.io/gcr-for-testing/alpine:3.17"
  starterModes:
    type: string
    default: "single,cluster,activefailover"

executors:
  golang-executor:
    docker:
      - image: gcr.io/gcr-for-testing/golang:1.20.7
  machine-executor:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

jobs:
  check-code:
    executor: golang-executor
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: make init
      - run: make check
      - run: make binaries
      - run: make vulncheck

  run-tests:
    executor: machine-executor
    steps:
      - checkout
      - run:
          name: Run-tests
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "This is not a pull request. Skipping..."
              exit 0
            fi
            make run-tests
    environment:
      ARANGODB: << pipeline.parameters.arangodbImage >>
      GOIMAGE: << pipeline.parameters.goImage >>
      ALPINE_IMAGE: << pipeline.parameters.alpineImage >>
      STARTER_MODES: << pipeline.parameters.starterModes >>
      MULTIARCH: 0
      VERBOSE: 1

workflows:
  version: 2

  run_always:
    jobs:
      - check-code
      - run-tests
